version: "3.9"

services:
  jqplay:
    build: .
    depends_on:
      - db
    restart: always
    ports:
      - "8080"
    environment:
      DATABASE_URL: "postgres://jqplay-user:jqplay-pass@db/jqplay-db?sslmode=disable"
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: jqplay-user
      POSTGRES_PASSWORD: jqplay-pass
      POSTGRES_DB: jqplay-db
