version: "3.9"

services:
  jqplay:
    image: registry.jackoxi.systems/public-images/jq-play-server:latest
    depends_on:
      - db
    restart: always
    ports:
      - "8080"
    environment:
      DATABASE_URL: "postgres://jqplay-user:jqplay-pass@db/jqplay-db?sslmode=disable"
      DATABASE_DRIVER: "postgres"
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: jqplay-user
      POSTGRES_PASSWORD: jqplay-pass
      POSTGRES_DB: jqplay-db